// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false
};

export const FCTSDashBoard = {
  WRApiV1: "/api/v1/webreports/",
  WFApiV2: '/api/v2/',
  WFApiV1: '/api/v1/',
  //WRApiV1: "/api/v1/nodes/",
  WRApiV2: "/output",
  getMenuCountExt: "CTASidebarExtCount",
  getDashboardInbox: "35872", // Not found 
  getUserOverallData: "CTAUserDataDashboard",
  ExternalInbNew: "CTA_Dash_ExtInbNew",
  ExternalFullSearch: "CTA_ExtFullSearch",
  DashboardReportMain: "CTA_DashboardWR",
  BravaURL: 'CTA_DocPreview', 
  SearchFilters: 'CTA_SearchFilters',
  SenderInfo: 'CTA_SenderInfoRO',
  RecipientInfo: 'CTA_RecipientInfoRO',
  CCInfo: 'CTA_CCInfoRO',
  CoverSectionInfo: 'CTA_CoverSectionInfoRO',
  AttachmentSectionInfo: 'CTA_AttachSectionInfoRO',
  ExtOrgNameFilter: 'CTA_ExtOrgNameFilter',
  TransferAttributes: 'CTA_TransferAttributes',
  GetTransferFields: 'CTA_GetParticipantInfoByName',
  getcorrespondenceinfoRO: 'CTA_GetCorrInfoRO',
  WfAuditReport: 'CTA_AuditReportWF',
  TransferAuditReport: 'CTA_AuditReportTransfer',
  TransferHistoryTab: 'CTA_TransferTab',
  getMenuCountInt: 'CTASidebarIntCount',
  createTransfer: 'CTA_SetTranferUsers',
  GetCorrRecordData: 'CTA_GetCorrRecordData',
  GetCorrFolderName: 'CTA_GetCorrFolderName',
  UserCollaborationRO: 'CTA_UserCollaborationRO',
  WorkflowCommentsList: 'CTA_WFCommentsList',
  CorrConnectionsList: 'CTA_CorrConnectionsList',
  PropertiesURL: 'PropertiesWidget',
  DefaultPageSize: 10,
  SetPerformerPermission: 'CTA_SetPerformPerm', /* added PSM: 22/06/2019 */
  SetStatuses: 'CTA_SetStatus', //added 01/07/2019,
  OrgChart: 'CTA_orgmd',
  /* added last time*/
  CheckWFRecall: 'FCTS_CheckWFRecall',
  GetTransferUsers: 'CTA_GetTransferUsers',
  GetTransRecallData: 'FCTS_GetTransRecallData',
  RunTransferRecall: 'FCTS_RunTransRecall',
  RunWFRecall: 'FCTS_RunWFRecall',
  SendRecallEmail: 'FCTS_SendRecallEmail',
  SetDipsAudit: 'FCTS_SetDipsAudit',
  SetStatusMultiApprove: 'FCTS_SetStatusMultiApprove',
  SetTransStatus: 'FCTS_UpdTransStatus',
  GetGlobalConst: 'CTA_ConstantsObject',
  UserInfo: '801145',
  searchFieldautoFill: '801149',
  CoverFolderContents: '801263',
  AttachmentFolderContents: '801271',
  createTempAttachments: '801141',
  initiateIncomingWF: '866431', 
  GenerateBarcode: '866432',
  GetCCUserSet: '866434',
  getMenuCountMR: 'CTA_SidebarMRCount',
  CCRecallReturnToAS: 'FCTS_CCRecall',
  GetUserMailroomPrivelage: '866435',
  GetApproverList: '866436',
  GetCoverLettertemplates: '866437',
  GetColUserSet: '866438',
  initiateOutgoingWF: '866439',
  syncDoc: 'syncdoc',
  insertNotes: '1008278',
  getNotes: '1008280',
  getWFTaskInfo: '1264991',
  //BaseHref: '/img/fctsangular/fctsapp/',
  SelectAttributes: '801367',
  InsertNewComment: '801071',
  DeleteComment: '801075',
  setConnection: '801383',
  getCorrespondenceFormValues: '801379',
  setSubfolderPerm: 'CTA_SetSubfolderPerm',
  documentTranlsation: '866482',  
  copyfromcsurl: '801391',
  folderbrowserurl: '801395',
  initiateInternalWF: '866440', 
  ProxyInfo: 'CTA_ProxyUserInfo',
  // BaseHref: '/img/fctsangular/fctsapp/', 
  PerformerInfo: '801475',
  UserGroups: '866379', 

  AddDelegation: '801516',
  DelegationsActivator: '801524',
  CurrentDelegations: '801528',
  DelegationsInactivator: '801540',
  DelegationsReport: '801536',
  CorrespondenceRelated: 'CTA_CorrespondenceRelated',
  DeleteConnection: 'CTA_DeleteConnection',
  DocumentsRelated: 'CTA_DocumentsRelated',
  ConnectionsParentChild: 'CTA_ConnectionsParentChild',
  FilesSerch: 'CTA_FilesSerch',
  InsertConnection: '       CTA_InsertConnection',
  ConnectionsSearch: 'CTA_ConnectionsSearch',
  InsertMultipleConnections: 'CTA_InsertMultipleConnections',
  GetParentData: 'CTA_GetParentData',
  FolderFiles: 'CTA_FolderFiles',
  CorrespondenceRelatedShort: 'CTA_CorrespondenceRelatedShort',
 
  DownloadAttachmentsBox: 'CTA_DownloadAttachments',
  CopySelectedFiles: 'ExtractAllAttachments',
  SetAttDownloadPermissions: 'CTA_SetAttDownloadPermissions',
  ECMDChart: 'CTA_ECMDChart',
  ECMDSearch: 'CTA_ECDM_Search',
  ExportCorrespondence: 'CTA_ExportCorrespondence',
  FilterValuesSearch: 'CTA_FilterValuesSearch',
  ApproveData: 'CTA_ApproveData',
  MultiAppAutoFill: 'CTA_MultiAppAutoFill',
  SetMultiApprovers: 'CTA_SetMultiApprovers',
  DistributionSection: 'CTA_DistributionSection',
  DistributionsChart: 'CTA_DistributionsChart',
  DistributionsChartEmployees: 'CTA_DistributionsChartEmployees',
  GetDistributionUsers: 'CTA_GetDistributionUsers',
  //ECMDepartmentsSearch: 'CTA_ECDMDepartments_Search',
  CloseMe: '%2Fimg%2Fcsui%2Fpages%2Fclose.html',
  GetTeams: 'CTA_GetTeams',
  //BaseHref: '/img/fctsangular/fctsapp/',
  BaseHref: '/',
  CSUrlShort: '172.18.169.245',

  CSUrl: 'http://manotctsdev.mannaicorp.com.qa/otcs/cs.exe'
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
